colorscheme: light

nav:
  home: /
  tag: /tags/
  category: /categories/
  Archives: /archives/
  about: /about/

social_links:
  -
    icon: github
    link: https://github.com/gsxhnd

rss:

cdn:
  enable: false